#!/bin/bash
set -euo pipefail

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

cd /usr/share/X11/xkb

echo "Copying dk_mac_fixed"
sudo cp "$dir"/dk_mac_fixed symbols/

if grep dk_mac_fixed rules/evdev.xml > /dev/null; then
    exit
fi

echo "Adding dk_mac_fixed layout to evdev.xml"

read -r -d '' layout <<EOF || true
<!-- BEGIN dk_mac_fixed -->
    <layout>
      <configItem>
        <name>dk_mac_fixed</name>

        <shortDescription>dk_mac_fixed</shortDescription>
        <description>Danish (Fixed Macintosh, no dead keys)</description>
        <languageList>
          <iso639Id>dan</iso639Id>
        </languageList>
      </configItem>
    </layout>
<!-- END dk_mac_fixed -->
EOF

tmp=$(mktemp)
awk -v layout="$layout" '{ print } /<layoutList>/ { print layout }' rules/evdev.xml > "$tmp"
sudo mv "$tmp" rules/evdev.xml
